## 1. Import the preprocessed dataset

```{r, cache = T}
if(!file.exists("sample.csv"))
{
    source("preprocess.r")
}
profiles <- read.csv("sample.csv")

#wanted_profiles <- subset(profiles, age <= 30)
```


## 2. Sentiment Analysis

```{r, warning=FALSE, message = FALSE, fig.width = 12}
library(ggplot2)

ggplot(profiles) +
    aes(x = polarity, y = wc) + 
    geom_point() + 
    ggtitle("Word Count vs. Sentiment")
```

Clearly there are exponential growth curve lines with multiple levels, but we currently have no idea what these groups correspond to. For interactive parts, we can just have them color by multiple variables, trying to ascertain if there is any underlying group structure.

```{r, fig.width = 12, warning=FALSE}
correlation <- cor(profiles$income, profiles$age, use = "na.or.complete") ** 2

mytext <- paste("Age vs. Income with", "r^2 = ", correlation, ", colored by polarity")

ggplot(subset(profiles, income < 250000 & income > 0)) + 
    aes(x = age, y = income) + 
    geom_point(aes(colour = polarity)) + 
    scale_colour_gradientn(colours=c("#FF0000", "#ffffff", "#440088","#0000FF")) + 
    geom_smooth(method = "lm") + 
    ggtitle(mytext)
```

# 3. Word Frequency Analysis

```{r}
# adapted from http://www.amstat.org/publications/jse/v23n2/kim.pdf
ggplot(profiles) +
    geom_point(aes(x = alcohol, 
                   y = drinks, 
                   size = polarity  * 1.5, 
                   colour = polarity)) +
    labs(x = "Number of Alcoholic Words", y = "Drinking Behavior")
```
